# Generated by Django 3.0.1 on 2020-03-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200312_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
