# Generated by Django 3.0.1 on 2020-04-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='./media/Author.jpg', null=True, upload_to='Profiles'),
        ),
    ]
