# Generated by Django 3.0.1 on 2020-03-03 08:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True, unique_for_date='publish')),
                ('description', models.TextField()),
                ('job_url', models.URLField()),
                ('thumbnail', models.ImageField(default='jobs.png', upload_to='Jobs %Y%M%d')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
