# Generated by Django 3.0.1 on 2020-03-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='thumbnail',
        ),
    ]
