# Generated by Django 3.0.1 on 2020-03-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200305_0551'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.CharField(default='education', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
