# Generated by Django 3.0.1 on 2020-03-05 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200305_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='categories',
            new_name='category',
        ),
    ]
