# Generated by Django 3.0.1 on 2020-03-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20200305_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='jobs', max_length=200),
            preserve_default=False,
        ),
    ]
