# Generated by Django 3.0.1 on 2020-03-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20200305_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('publish',)},
        ),
        migrations.AddField(
            model_name='job',
            name='body',
            field=models.TextField(default='body'),
            preserve_default=False,
        ),
    ]
