# Generated by Django 3.0.1 on 2020-03-10 06:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20200305_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('-publish',)},
        ),
        migrations.AlterField(
            model_name='job',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
