# Generated by Django 3.0.1 on 2020-03-18 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_job_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tags',
        ),
    ]
