# Generated by Django 3.0.1 on 2020-04-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_remove_job_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='Logos %Y%M%d'),
        ),
    ]
