# Generated by Django 3.0.1 on 2021-02-21 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20210203_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('logo', models.ImageField(default='logo.png', upload_to='Company/Logos')),
            ],
        ),
        migrations.AlterModelManagers(
            name='job',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('contract', 'Contract'), ('fulltime', 'Fulltime'), ('remote', 'Remote')], default='fulltime', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='expiry',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('nairobi', 'Nairobi'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru'), ('eldoret', 'Eldoret'), ('kakamega', 'Kakamega')], default='nairobi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(default='confidential', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pulished', 'Published')], default='draft', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Company'),
        ),
    ]
