# Generated by Django 3.0.1 on 2021-02-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20210221_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='thumbnail',
        ),
        migrations.AlterField(
            model_name='job',
            name='job_url',
            field=models.URLField(default='https://jobsearchke.com/'),
        ),
    ]
