# Generated by Django 3.0.1 on 2021-02-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_auto_20210221_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('sales & marketing', 'Sales/Marketting'), ('accounting & finance', 'Accounting/Finance'), ('software engineering', 'Software/Engineering'), ('ict & telecommunications', 'ICT/Telecommunications'), ('manufacturing & production', 'Manufacturing/Production'), ('ngo', 'NGO'), ('education & teaching', 'Education/Teaching'), ('media & social_media', 'Media/Social_Media'), ('healthcare & medical', 'Healthcare/Medical'), ('banking & insurance', 'Banking/Insurance'), ('logistics & procurement', 'Logistics/Procurement'), ('internship', 'Internship'), ('hotels & hospitality', 'Hotels/Hospitality'), ('government & parastatals', 'Government/Parastatals'), ('management', 'Management'), ('data science', 'Data Science'), ('hr & admin assistant', 'HR/Admin Assistant')], max_length=256),
        ),
    ]
