# Generated by Django 3.0.1 on 2021-03-05 09:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_auto_20210221_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='apply',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('sales & marketing', 'Sales/Marketting'), ('accounting & finance', 'Accounting/Finance'), ('software engineering', 'Software/Engineering'), ('ict & telecommunications', 'ICT/Telecommunications'), ('manufacturing & production', 'Manufacturing/Production'), ('ngo', 'NGO'), ('education & teaching', 'Education/Teaching'), ('media & social_media', 'Media/Social_Media'), ('healthcare & medical', 'Healthcare/Medical'), ('banking & insurance', 'Banking/Insurance'), ('logistics & procurement', 'Logistics/Procurement'), ('internship', 'Internship'), ('hotels & hospitality', 'Hotels/Hospitality'), ('government & parastatals', 'Government/Parastatals'), ('management', 'Management'), ('data science', 'Data Science'), ('hr & admin assistant', 'HR/Admin Assistant'), ('customer service', 'Customer Service'), ('engineering', 'Engineering')], max_length=256),
        ),
    ]
