# Generated by Django 3.0.1 on 2021-03-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_auto_20210305_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(default='str', max_length=50),
            preserve_default=False,
        ),
    ]
