# Generated by Django 3.0.1 on 2021-03-10 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='apply',
        ),
    ]
