# Generated by Django 3.0.1 on 2022-01-01 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_job_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10, null=True),
        ),
    ]
