# Generated by Django 3.0.1 on 2020-04-15 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corporate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('job_url', models.URLField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Jobskenya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('date_posted', models.CharField(max_length=50)),
                ('job_url', models.URLField()),
                ('description', models.TextField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Myjobmag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('job_url', models.URLField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
