# Generated by Django 3.0.1 on 2020-05-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='icon',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
    ]
