# Generated by Django 3.0.1 on 2020-03-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('interviews', 'INTERVIEWS'), ('career_development', 'CAREER_DEVELOPMENT'), ('resumes', 'RESUMES'), ('salaries', 'SALARIES')], default='interviews', max_length=100),
        ),
    ]
